apiVersion: v1
kind: Pod
metadata:
  name: nginx-badtux
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: nginx-badtux
      image: nginx:alpine
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1